from .GRPromptReplacerAttributesBasic import (
    NODE_CLASS_MAPPINGS as BASIC_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BASIC_DISPLAY_NAME_MAPPINGS,
)
from .GRPromptReplacerAttributesMulti import (
    NODE_CLASS_MAPPINGS as MULTI_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MULTI_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **BASIC_CLASS_MAPPINGS,
    **MULTI_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **BASIC_DISPLAY_NAME_MAPPINGS,
    **MULTI_DISPLAY_NAME_MAPPINGS,
}

# Tells ComfyUI where to find this package's front-end JS (gr_multi_select_widget.js).
WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
